# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20190112_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='albumimage',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='checkin',
            name='nid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
