# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20190112_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='file',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='url',
            name='slug',
        ),
        migrations.AddField(
            model_name='album',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='choice',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='file',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='poll',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='post',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='url',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
