# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0004_auto_20190112_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicerecord_users', to=settings.AUTH_USER_MODEL)),
                ('chice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='club.Choice')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('category', 'date')},
        ),
    ]
