# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20190114_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='context',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
